# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComposableArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComposableArchitecture
   pod 'RxSwift', '~> 5'
   pod 'RxCocoa', '~> 5'

  target 'ComposableArchitectureTests' do
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    
  end

end

target 'Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Counter
   pod 'RxSwift', '~> 5'
   pod 'RxCocoa', '~> 5'
   pod 'SwiftSpinner'#, '~> 1.5.0'

  target 'CounterTests' do
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    
  end

end

target 'RxPrimeTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxPrimeTime
   pod 'RxSwift', '~> 5'
   pod 'RxCocoa', '~> 5'
   pod 'SwiftSpinner'#, '~> 1.5.0'

  target 'RxPrimeTimeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    
  end

end
